### ISSUE TITLE
load pre-training weights to the model

### ISSUE THREAD

**Issue by JackyWang2001** [sail-sg/VGT#1]
Thanks for your insightful work. 
I read that VGT has better performance with pre-training on WebVideo. I would like to know how to run the code to load the pre-trained weights you provide in [WebVideo0.18M](https://drive.google.com/file/d/1xvKFUHGrRz8gtv2jPE-2T4ug89fyX7zO/view).

**Comment by doc-doc** [comment]
Thanks for the interest. You can uncomment the "CM_PT" and “pretrained_path” to the pretrained weight in the shell scripts next_train.sh

**Comment by junwenchen** [comment]
Hi,

In L496-500 of vqa_model.py, I realized that graph_trans_n (with cm pretrain) and graph_trans are initialized with the same config. Could you please let me know how the cm pretrained weights are loaded?

**Comment by junwenchen** [comment]
Hi, 

Can you let me know where I can get accessed to the webvideo0.18M dataset?

**Comment by doc-doc** [comment]
Hi, you need to download the raw data (train&val) from [WebVid2.5M](https://m-bain.github.io/webvid-dataset/) (provide links only). The videoid of the subset (0.18M) used in this paper can be found [here](https://drive.google.com/file/d/1j5fN0frayrqDFao582zP10YcDKV9Q8R4/view?usp=sharing).  You can map the videoid to the 2.5M file and get the URLs. Note that we can only provide the links. The raw video and the extracted feature are really large, and we are unable to share it online.

**Comment by JackyWang2001** [comment]
Thank you for answering. I am now able to re-implement it.
