### ISSUE TITLE
The links for pre-computed features for TGIF-QA (Trans) and TGIF-QA (FrameQA) are not working.

### ISSUE THREAD

**Issue by ahmadmobeen** [sail-sg/VGT#3]

**Comment by doc-doc** [comment]
Yes, you need to email us for temporal access to needed feature since we do not have enough online storage to share..

**Comment by ahmadmobeen** [comment]
I have sent the email for the needed features. Thank you.

**Comment by accebet** [comment]
Hi, could you provide the feature files to me, please?
